int main(){
    char a[101];
    gets(a);
    int i,k;
    for(i=0;a[i]!='\0';i++){
        if(a[i]==32&&a[i+1]==32){
            for(k=i;a[k]!='\0';k++){
            a[k+1]=a[k+2];
            }
        }
    }
        for(i=0;a[i]!='\0';i++){
        if(a[i]==32&&a[i+1]==32){
            for(k=i;a[k]!='\0';k++){
            a[k+1]=a[k+2];
            }
        }
    }
   for(i=0;a[i]!='\0';i++){
        if(a[i]==32&&a[i+1]==32){
            for(k=i;a[k]!='\0';k++){
            a[k+1]=a[k+2];
            }
        }
    }
       for(i=0;a[i]!='\0';i++){
        if(a[i]==32&&a[i+1]==32){
            for(k=i;a[k]!='\0';k++){
            a[k+1]=a[k+2];
            }
        }
    }
       for(i=0;a[i]!='\0';i++){
        if(a[i]==32&&a[i+1]==32){
            for(k=i;a[k]!='\0';k++){
            a[k+1]=a[k+2];
            }
        }
    }
       for(i=0;a[i]!='\0';i++){
        if(a[i]==32&&a[i+1]==32){
            for(k=i;a[k]!='\0';k++){
            a[k+1]=a[k+2];
            }
        }
    }
       for(i=0;a[i]!='\0';i++){
        if(a[i]==32&&a[i+1]==32){
            for(k=i;a[k]!='\0';k++){
            a[k+1]=a[k+2];
            }
        }
    }
       for(i=0;a[i]!='\0';i++){
        if(a[i]==32&&a[i+1]==32){
            for(k=i;a[k]!='\0';k++){
            a[k+1]=a[k+2];
            }
        }
    }
    puts(a);
    return 0;
}
