int main()
{
 char str[301];
 char*by;
 by=str;
 int a=0,b=0,c=0,d=0,e=0,f=0,g=0,h=0,i=0,j=0,k=0,l=0,m=0,n=0,o=0,p=0,q=0,r=0,s=0,t=0,u=0,v=0,w=0,x=0,y=0,z=0;
scanf("%s",str);
 for(;*by!='\0';by++)
{
 if(*by=='a'){a++;}
if(*by=='b'){b++;}
if(*by=='c'){c++;}
if(*by=='d'){d++;}
if(*by=='e'){e++;}
if(*by=='f'){f++;}
if(*by=='g'){g++;}
if(*by=='h'){h++;}
if(*by=='i'){i++;}
if(*by=='j'){j++;}
if(*by=='k'){k++;}
if(*by=='l'){l++;}
if(*by=='m'){m++;}
if(*by=='n'){n++;}
if(*by=='o'){o++;}
if(*by=='p'){p++;}
if(*by=='q'){q++;}
if(*by=='r'){r++;}
if(*by=='s'){s++;}
if(*by=='t'){t++;}
if(*by=='u'){u++;}
if(*by=='v'){v++;}
if(*by=='w'){w++;}
if(*by=='x'){x++;}
if(*by=='y'){y++;}
if(*by=='z'){z++;}
}
if(a==0&&b==0&&c==0&&d==0&&e==0&&f==0&&g==0&&h==0&&i==0&&j==0&&k==0&&l==0&&m==0&&n==0&&o==0&&p==0&&q==0&&r==0&&s==0&&t==0&&u==0&&v==0&&w==0&&x==0&&y==0&&z==0){printf("No");}
 if(a!=0){printf("a=%d\n",a);}
 if(b!=0){printf("b=%d\n",b);}
if(c!=0){printf("c=%d\n",c);}
 if(d!=0){printf("d=%d\n",d);}
 if(e!=0){printf("e=%d\n",e);}
if(f!=0){printf("f=%d\n",f);}
 if(g!=0){printf("g=%d\n",g);}
 if(h!=0){printf("h=%d\n",h);}
if(i!=0){printf("i=%d\n",i);}
 if(j!=0){printf("j=%d\n",j);}
 if(k!=0){printf("k=%d\n",k);}
 if(l!=0){printf("l=%d\n",l);}
 if(m!=0){printf("m=%d\n",m);}
 if(n!=0){printf("n=%d\n",n);}
 if(p!=0){printf("p=%d\n",p);}
 if(q!=0){printf("q=%d\n",q);}
 if(r!=0){printf("r=%d\n",r);}
 if(s!=0){printf("s=%d\n",s);}
 if(t!=0){printf("t=%d\n",t);}
 if(u!=0){printf("u=%d\n",u);}
 if(v!=0){printf("v=%d\n",v);}
 if(w!=0){printf("w=%d\n",w);}
 if(x!=0){printf("x=%d\n",x);}
 if(y!=0){printf("y=%d\n",y);}
 if(z!=0){printf("z=%d\n",z);}
return 0;
}
